<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Satooshi\\Component' => array($vendorDir . '/satooshi/php-coveralls/src'),
    'Satooshi\\Bundle' => array($vendorDir . '/satooshi/php-coveralls/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'ParaTest' => array($vendorDir . '/brianium/paratest/src'),
    'Habitat' => array($vendorDir . '/brianium/habitat/src'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    '' => array($vendorDir . '/brianium/paratest/test/unit', $vendorDir . '/brianium/paratest/test/functional'),
);
